# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  - 5.2

env:
  - DB=mysql

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi
# optionally specify a list of environments, for example to test different RDBMS
script: phpunit --configuration phpunit_$DB.xml --coverage-text

after_success:
    "wget -r ftp://ftp.checkdemo.com/ --user test@checkdemo.com --password Cc.7dhtr7"
# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "mani@creativeindia.net.in"
